# Generated by Django 6.0.5 on 2026-05-14 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Budget', 'Budget'), ('Premium', 'Premium'), ('Luxury', 'Luxury'), ('Family', 'Family-Friendly')], max_length=50)),
                ('trust_score', models.IntegerField(help_text='Score out of 100')),
                ('is_verified', models.BooleanField(default=False)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='trip_planner.location')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avg_cost_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuisine_type', models.CharField(max_length=200)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_tourist_safe', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='trip_planner.location')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Score out of 100')),
                ('scam_risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('safe_zones', models.TextField(blank=True, help_text='List of safe zones')),
                ('scam_hotspots', models.TextField(blank=True, help_text='Areas to avoid')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_score', to='trip_planner.location')),
            ],
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='e.g., Waterfall, Trekking, Historical, Nature', max_length=100)),
                ('estimated_time_spent', models.CharField(help_text='e.g., 2 hours', max_length=100)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_safe', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_places', to='trip_planner.location')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_str', models.CharField(help_text='e.g. 09:00 AM - 11:00 AM', max_length=50)),
                ('activity_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trip_planner.itinerary')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip_planner.touristplace')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('group_type', models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends')], max_length=20)),
                ('preferences', models.TextField(help_text='Comma separated interests like waterfalls, trekking, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip_planner.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_time_mins', models.IntegerField(help_text='Time in minutes')),
                ('transport_mode', models.CharField(choices=[('Taxi', 'Taxi'), ('Bus', 'Bus'), ('Train', 'Train'), ('Walking', 'Walking')], max_length=100)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_safe_route', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_routes', to='trip_planner.trip')),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trip_planner.trip'),
        ),
        migrations.CreateModel(
            name='BudgetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_hotel_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_food_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_transport_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_activities_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emergency_buffer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_estimated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('luxury_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_analysis', to='trip_planner.trip')),
            ],
        ),
    ]
