# Generated by Django 6.0.5 on 2026-05-13 06:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('taxi', 'Taxi/Transport'), ('hotel', 'Hotel/Accommodation'), ('shop', 'Shop/Market'), ('tour_guide', 'Tour Guide'), ('travel_agency', 'Travel Agency'), ('street_food', 'Street Food'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendors/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('trust_score', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('safety_rating', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('scam_reports_count', models.PositiveIntegerField(default=0)),
                ('positive_reviews', models.PositiveIntegerField(default=0)),
                ('negative_reviews', models.PositiveIntegerField(default=0)),
                ('price_range', models.CharField(choices=[('$', 'Budget'), ('$$', 'Mid-range'), ('$$$', 'Premium'), ('$$$$', 'Luxury')], default='$$', max_length=10)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_vendors', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trust_score'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_scam_related', models.BooleanField(default=False)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category', 'is_verified'], name='vendors_ven_categor_2cdacf_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['city', 'country'], name='vendors_ven_city_cff5fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('vendor', 'user')},
        ),
    ]
