# Generated by Django 6.0.5 on 2026-05-13 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bills/')),
                ('bill_type', models.CharField(choices=[('taxi', 'Taxi Bill'), ('restaurant', 'Restaurant Bill'), ('hotel', 'Hotel Bill'), ('shopping', 'Shopping Bill'), ('other', 'Other')], max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('items_detected', models.JSONField(default=list)),
                ('total_detected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes_detected', models.JSONField(default=list)),
                ('suspicious_charges', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('fair_price_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scam_probability', models.FloatField(default=0.0)),
                ('analysis_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='scams.bill')),
            ],
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('taxi', 'Taxi/Transport Scam'), ('restaurant', 'Restaurant Overcharging'), ('shopping', 'Shopping/Product Scam'), ('tour_guide', 'Fake Tour Guide'), ('accommodation', 'Accommodation Fraud'), ('street_vendor', 'Street Vendor Scam'), ('currency', 'Currency Exchange Scam'), ('ticket', 'Fake Tickets'), ('pickpocket', 'Pickpocket/Theft'), ('other', 'Other Scam')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scam_reports/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='scam_reports/')),
                ('charged_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('ai_summary', models.TextField(blank=True)),
                ('scam_probability', models.FloatField(default=0.0)),
                ('ai_risk_score', models.FloatField(default=0.0)),
                ('ai_classification', models.CharField(blank=True, max_length=50)),
                ('is_ai_analyzed', models.BooleanField(default=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('incident_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scam_reports', to='scams.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('scam_detection', 'Scam Detection'), ('price_verification', 'Price Verification'), ('bill_analysis', 'Bill Analysis'), ('similarity_check', 'Similarity Check'), ('risk_assessment', 'Risk Assessment')], max_length=30)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='llama-3.3-70b-versatile', max_length=50)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='scams.bill')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='scams.scamreport')),
            ],
            options={
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScamVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='scams.scamreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['category', 'status'], name='scams_scamr_categor_f0981b_idx'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['latitude', 'longitude'], name='scams_scamr_latitud_7f720c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scamvote',
            unique_together={('user', 'report')},
        ),
    ]
